# Use this profile for development purposes only.
#
spring:
  security:
    oauth2:
      client:
        provider:
          my-auth-provider:
            issuer-uri: http://localhost:5556
        registration:
          messaging-client:
            provider: my-auth-provider
            client-id: base-client
            client-secret: base-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/dex"
            scope:
            - openid
            - email
            - profile
            client-name: Dex IDP
  docker:
    compose:
      file: compose.yaml