apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
  name: appsso-starter-java
  namespace: workloads
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: live-update
      value: "true"
  serviceClaims:
    - name: appsso-starter-java
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: appsso-starter-java
  source:
    git:
      url: https://github.com/Kehrlann/tap-workload-experiments
      ref:
        branch: main
    subPath: appsso-starter-java
