apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: server-side-ui-starter
  namespace: workloads
spec:
  classRef:
    name: ci
  parameters:
    authorizationGrantTypes:
    - client_credentials
    - authorization_code
    - refresh_token
    clientAuthenticationMethod: client_secret_basic
    displayName: AppSSO Starter Java
    redirectPaths:
    - /login/oauth2/code/server-side-ui-starter
    requireUserConsent: true
    scopes:
    - name: openid
    - name: profile
    - name: email
    - description: bestows the ultimate power
      name: coffee.make
    workloadRef:
      name: server-side-ui-starter
