apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: server-side-ui-starter
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: server-side-ui-starter
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  serviceClaims:
    - name: server-side-ui-starter
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: server-side-ui-starter
